const colors = require("tailwindcss/colors");

function withOpacityValue(variable) {
  return ({ opacityValue }) => {
    if (opacityValue === undefined) {
      return `rgb(var(${variable}))`;
    }
    return `rgb(var(${variable}) / ${opacityValue})`;
  };
}

module.exports = {
  content: ["./public/**/*.html", "./src/**/*.js"],
  theme: {
    extend: {
      backgroundImage: {
        avatar: "url('/src/svgs/avatar.svg')",
      },
      colors: {
        gray0: withOpacityValue("--gray0"),
        gray1: withOpacityValue("--gray1"),
        gray2: withOpacityValue("--gray2"),
        gray3: withOpacityValue("--gray3"),
        gray4: withOpacityValue("--gray4"),
        gray5: withOpacityValue("--gray5"),
        gray6: withOpacityValue("--gray6"),
        gray7: withOpacityValue("--gray7"),
        gray8: withOpacityValue("--gray8"),
        gray9: withOpacityValue("--gray9"),
        red0: withOpacityValue("--red0"),
        red1: withOpacityValue("--red1"),
        red2: withOpacityValue("--red2"),
        red3: withOpacityValue("--red3"),
        red4: withOpacityValue("--red4"),
        red5: withOpacityValue("--red5"),
        red6: withOpacityValue("--red6"),
        red7: withOpacityValue("--red7"),
        red8: withOpacityValue("--red8"),
        red9: withOpacityValue("--red9"),
        orange0: withOpacityValue("--orange0"),
        orange1: withOpacityValue("--orange1"),
        orange2: withOpacityValue("--orange2"),
        orange3: withOpacityValue("--orange3"),
        orange4: withOpacityValue("--orange4"),
        orange5: withOpacityValue("--orange5"),
        orange6: withOpacityValue("--orange6"),
        orange7: withOpacityValue("--orange7"),
        orange8: withOpacityValue("--orange8"),
        orange9: withOpacityValue("--orange9"),
        amber0: withOpacityValue("--amber0"),
        amber1: withOpacityValue("--amber1"),
        amber2: withOpacityValue("--amber2"),
        amber3: withOpacityValue("--amber3"),
        amber4: withOpacityValue("--amber4"),
        amber5: withOpacityValue("--amber5"),
        amber6: withOpacityValue("--amber6"),
        amber7: withOpacityValue("--amber7"),
        amber8: withOpacityValue("--amber8"),
        amber9: withOpacityValue("--amber9"),
        yellow0: withOpacityValue("--yellow0"),
        yellow1: withOpacityValue("--yellow1"),
        yellow2: withOpacityValue("--yellow2"),
        yellow3: withOpacityValue("--yellow3"),
        yellow4: withOpacityValue("--yellow4"),
        yellow5: withOpacityValue("--yellow5"),
        yellow6: withOpacityValue("--yellow6"),
        yellow7: withOpacityValue("--yellow7"),
        yellow8: withOpacityValue("--yellow8"),
        yellow9: withOpacityValue("--yellow9"),
        lime0: withOpacityValue("--lime0"),
        lime1: withOpacityValue("--lime1"),
        lime2: withOpacityValue("--lime2"),
        lime3: withOpacityValue("--lime3"),
        lime4: withOpacityValue("--lime4"),
        lime5: withOpacityValue("--lime5"),
        lime6: withOpacityValue("--lime6"),
        lime7: withOpacityValue("--lime7"),
        lime8: withOpacityValue("--lime8"),
        lime9: withOpacityValue("--lime9"),
        green0: withOpacityValue("--green0"),
        green1: withOpacityValue("--green1"),
        green2: withOpacityValue("--green2"),
        green3: withOpacityValue("--green3"),
        green4: withOpacityValue("--green4"),
        green5: withOpacityValue("--green5"),
        green6: withOpacityValue("--green6"),
        green7: withOpacityValue("--green7"),
        green8: withOpacityValue("--green8"),
        green9: withOpacityValue("--green9"),
        emerald0: withOpacityValue("--emerald0"),
        emerald1: withOpacityValue("--emerald1"),
        emerald2: withOpacityValue("--emerald2"),
        emerald3: withOpacityValue("--emerald3"),
        emerald4: withOpacityValue("--emerald4"),
        emerald5: withOpacityValue("--emerald5"),
        emerald6: withOpacityValue("--emerald6"),
        emerald7: withOpacityValue("--emerald7"),
        emerald8: withOpacityValue("--emerald8"),
        emerald9: withOpacityValue("--emerald9"),
        teal0: withOpacityValue("--teal0"),
        teal1: withOpacityValue("--teal1"),
        teal2: withOpacityValue("--teal2"),
        teal3: withOpacityValue("--teal3"),
        teal4: withOpacityValue("--teal4"),
        teal5: withOpacityValue("--teal5"),
        teal6: withOpacityValue("--teal6"),
        teal7: withOpacityValue("--teal7"),
        teal8: withOpacityValue("--teal8"),
        teal9: withOpacityValue("--teal9"),
        cyan0: withOpacityValue("--cyan0"),
        cyan1: withOpacityValue("--cyan1"),
        cyan2: withOpacityValue("--cyan2"),
        cyan3: withOpacityValue("--cyan3"),
        cyan4: withOpacityValue("--cyan4"),
        cyan5: withOpacityValue("--cyan5"),
        cyan6: withOpacityValue("--cyan6"),
        cyan7: withOpacityValue("--cyan7"),
        cyan8: withOpacityValue("--cyan8"),
        cyan9: withOpacityValue("--cyan9"),
        sky0: withOpacityValue("--sky0"),
        sky1: withOpacityValue("--sky1"),
        sky2: withOpacityValue("--sky2"),
        sky3: withOpacityValue("--sky3"),
        sky4: withOpacityValue("--sky4"),
        sky5: withOpacityValue("--sky5"),
        sky6: withOpacityValue("--sky6"),
        sky7: withOpacityValue("--sky7"),
        sky8: withOpacityValue("--sky8"),
        sky9: withOpacityValue("--sky9"),
        blue0: withOpacityValue("--blue0"),
        blue1: withOpacityValue("--blue1"),
        blue2: withOpacityValue("--blue2"),
        blue3: withOpacityValue("--blue3"),
        blue4: withOpacityValue("--blue4"),
        blue5: withOpacityValue("--blue5"),
        blue6: withOpacityValue("--blue6"),
        blue7: withOpacityValue("--blue7"),
        blue8: withOpacityValue("--blue8"),
        blue9: withOpacityValue("--blue9"),
        indigo0: withOpacityValue("--indigo0"),
        indigo1: withOpacityValue("--indigo1"),
        indigo2: withOpacityValue("--indigo2"),
        indigo3: withOpacityValue("--indigo3"),
        indigo4: withOpacityValue("--indigo4"),
        indigo5: withOpacityValue("--indigo5"),
        indigo6: withOpacityValue("--indigo6"),
        indigo7: withOpacityValue("--indigo7"),
        indigo8: withOpacityValue("--indigo8"),
        indigo9: withOpacityValue("--indigo9"),
        violet0: withOpacityValue("--violet0"),
        violet1: withOpacityValue("--violet1"),
        violet2: withOpacityValue("--violet2"),
        violet3: withOpacityValue("--violet3"),
        violet4: withOpacityValue("--violet4"),
        violet5: withOpacityValue("--violet5"),
        violet6: withOpacityValue("--violet6"),
        violet7: withOpacityValue("--violet7"),
        violet8: withOpacityValue("--violet8"),
        violet9: withOpacityValue("--violet9"),
        purple0: withOpacityValue("--purple0"),
        purple1: withOpacityValue("--purple1"),
        purple2: withOpacityValue("--purple2"),
        purple3: withOpacityValue("--purple3"),
        purple4: withOpacityValue("--purple4"),
        purple5: withOpacityValue("--purple5"),
        purple6: withOpacityValue("--purple6"),
        purple7: withOpacityValue("--purple7"),
        purple8: withOpacityValue("--purple8"),
        purple9: withOpacityValue("--purple9"),
        fuchsia0: withOpacityValue("--fuchsia0"),
        fuchsia1: withOpacityValue("--fuchsia1"),
        fuchsia2: withOpacityValue("--fuchsia2"),
        fuchsia3: withOpacityValue("--fuchsia3"),
        fuchsia4: withOpacityValue("--fuchsia4"),
        fuchsia5: withOpacityValue("--fuchsia5"),
        fuchsia6: withOpacityValue("--fuchsia6"),
        fuchsia7: withOpacityValue("--fuchsia7"),
        fuchsia8: withOpacityValue("--fuchsia8"),
        fuchsia9: withOpacityValue("--fuchsia9"),
        pink0: withOpacityValue("--pink0"),
        pink1: withOpacityValue("--pink1"),
        pink2: withOpacityValue("--pink2"),
        pink3: withOpacityValue("--pink3"),
        pink4: withOpacityValue("--pink4"),
        pink5: withOpacityValue("--pink5"),
        pink6: withOpacityValue("--pink6"),
        pink7: withOpacityValue("--pink7"),
        pink8: withOpacityValue("--pink8"),
        pink9: withOpacityValue("--pink9"),
        rose0: withOpacityValue("--rose0"),
        rose1: withOpacityValue("--rose1"),
        rose2: withOpacityValue("--rose2"),
        rose3: withOpacityValue("--rose3"),
        rose4: withOpacityValue("--rose4"),
        rose5: withOpacityValue("--rose5"),
        rose6: withOpacityValue("--rose6"),
        rose7: withOpacityValue("--rose7"),
        rose8: withOpacityValue("--rose8"),
        rose9: withOpacityValue("--rose9"),
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/line-clamp"),
    require("@tailwindcss/aspect-ratio"),
  ],
};
