const colors = require("tailwindcss/colors");

const withOpacity =
  (variableName) =>
  ({ opacityVariable, opacityValue }) => {
    if (opacityValue !== undefined) {
      return `rgba(var(${variableName}), ${opacityValue})`;
    }
    if (opacityVariable !== undefined) {
      return `rgba(var(${variableName}), var(${opacityVariable}, 1))`;
    }
    return `rgb(var(${variableName}))`;
  };

module.exports = {
  mode: "jit",
  purge: {
    layers: ["components", "utilities"],
    content: ["./public/**/*.html", "./src/**/*.js"],
    options: {
      keyframes: true,
      fontFace: true,
    },
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      backgroundImage: {
        avatar: "url('/src/svgs/avatar.svg')",
      },
      colors: {
        gray0: withOpacity("--gray0"),
        gray1: withOpacity("--gray1"),
        gray2: withOpacity("--gray2"),
        gray3: withOpacity("--gray3"),
        gray4: withOpacity("--gray4"),
        gray5: withOpacity("--gray5"),
        gray6: withOpacity("--gray6"),
        gray7: withOpacity("--gray7"),
        gray8: withOpacity("--gray8"),
        gray9: withOpacity("--gray9"),
        red0: withOpacity("--red0"),
        red1: withOpacity("--red1"),
        red2: withOpacity("--red2"),
        red3: withOpacity("--red3"),
        red4: withOpacity("--red4"),
        red5: withOpacity("--red5"),
        red6: withOpacity("--red6"),
        red7: withOpacity("--red7"),
        red8: withOpacity("--red8"),
        red9: withOpacity("--red9"),
        orange0: withOpacity("--orange0"),
        orange1: withOpacity("--orange1"),
        orange2: withOpacity("--orange2"),
        orange3: withOpacity("--orange3"),
        orange4: withOpacity("--orange4"),
        orange5: withOpacity("--orange5"),
        orange6: withOpacity("--orange6"),
        orange7: withOpacity("--orange7"),
        orange8: withOpacity("--orange8"),
        orange9: withOpacity("--orange9"),
        amber0: withOpacity("--amber0"),
        amber1: withOpacity("--amber1"),
        amber2: withOpacity("--amber2"),
        amber3: withOpacity("--amber3"),
        amber4: withOpacity("--amber4"),
        amber5: withOpacity("--amber5"),
        amber6: withOpacity("--amber6"),
        amber7: withOpacity("--amber7"),
        amber8: withOpacity("--amber8"),
        amber9: withOpacity("--amber9"),
        yellow0: withOpacity("--yellow0"),
        yellow1: withOpacity("--yellow1"),
        yellow2: withOpacity("--yellow2"),
        yellow3: withOpacity("--yellow3"),
        yellow4: withOpacity("--yellow4"),
        yellow5: withOpacity("--yellow5"),
        yellow6: withOpacity("--yellow6"),
        yellow7: withOpacity("--yellow7"),
        yellow8: withOpacity("--yellow8"),
        yellow9: withOpacity("--yellow9"),
        lime0: withOpacity("--lime0"),
        lime1: withOpacity("--lime1"),
        lime2: withOpacity("--lime2"),
        lime3: withOpacity("--lime3"),
        lime4: withOpacity("--lime4"),
        lime5: withOpacity("--lime5"),
        lime6: withOpacity("--lime6"),
        lime7: withOpacity("--lime7"),
        lime8: withOpacity("--lime8"),
        lime9: withOpacity("--lime9"),
        green0: withOpacity("--green0"),
        green1: withOpacity("--green1"),
        green2: withOpacity("--green2"),
        green3: withOpacity("--green3"),
        green4: withOpacity("--green4"),
        green5: withOpacity("--green5"),
        green6: withOpacity("--green6"),
        green7: withOpacity("--green7"),
        green8: withOpacity("--green8"),
        green9: withOpacity("--green9"),
        emerald0: withOpacity("--emerald0"),
        emerald1: withOpacity("--emerald1"),
        emerald2: withOpacity("--emerald2"),
        emerald3: withOpacity("--emerald3"),
        emerald4: withOpacity("--emerald4"),
        emerald5: withOpacity("--emerald5"),
        emerald6: withOpacity("--emerald6"),
        emerald7: withOpacity("--emerald7"),
        emerald8: withOpacity("--emerald8"),
        emerald9: withOpacity("--emerald9"),
        teal0: withOpacity("--teal0"),
        teal1: withOpacity("--teal1"),
        teal2: withOpacity("--teal2"),
        teal3: withOpacity("--teal3"),
        teal4: withOpacity("--teal4"),
        teal5: withOpacity("--teal5"),
        teal6: withOpacity("--teal6"),
        teal7: withOpacity("--teal7"),
        teal8: withOpacity("--teal8"),
        teal9: withOpacity("--teal9"),
        cyan0: withOpacity("--cyan0"),
        cyan1: withOpacity("--cyan1"),
        cyan2: withOpacity("--cyan2"),
        cyan3: withOpacity("--cyan3"),
        cyan4: withOpacity("--cyan4"),
        cyan5: withOpacity("--cyan5"),
        cyan6: withOpacity("--cyan6"),
        cyan7: withOpacity("--cyan7"),
        cyan8: withOpacity("--cyan8"),
        cyan9: withOpacity("--cyan9"),
        sky0: withOpacity("--sky0"),
        sky1: withOpacity("--sky1"),
        sky2: withOpacity("--sky2"),
        sky3: withOpacity("--sky3"),
        sky4: withOpacity("--sky4"),
        sky5: withOpacity("--sky5"),
        sky6: withOpacity("--sky6"),
        sky7: withOpacity("--sky7"),
        sky8: withOpacity("--sky8"),
        sky9: withOpacity("--sky9"),
        blue0: withOpacity("--blue0"),
        blue1: withOpacity("--blue1"),
        blue2: withOpacity("--blue2"),
        blue3: withOpacity("--blue3"),
        blue4: withOpacity("--blue4"),
        blue5: withOpacity("--blue5"),
        blue6: withOpacity("--blue6"),
        blue7: withOpacity("--blue7"),
        blue8: withOpacity("--blue8"),
        blue9: withOpacity("--blue9"),
        indigo0: withOpacity("--indigo0"),
        indigo1: withOpacity("--indigo1"),
        indigo2: withOpacity("--indigo2"),
        indigo3: withOpacity("--indigo3"),
        indigo4: withOpacity("--indigo4"),
        indigo5: withOpacity("--indigo5"),
        indigo6: withOpacity("--indigo6"),
        indigo7: withOpacity("--indigo7"),
        indigo8: withOpacity("--indigo8"),
        indigo9: withOpacity("--indigo9"),
        violet0: withOpacity("--violet0"),
        violet1: withOpacity("--violet1"),
        violet2: withOpacity("--violet2"),
        violet3: withOpacity("--violet3"),
        violet4: withOpacity("--violet4"),
        violet5: withOpacity("--violet5"),
        violet6: withOpacity("--violet6"),
        violet7: withOpacity("--violet7"),
        violet8: withOpacity("--violet8"),
        violet9: withOpacity("--violet9"),
        purple0: withOpacity("--purple0"),
        purple1: withOpacity("--purple1"),
        purple2: withOpacity("--purple2"),
        purple3: withOpacity("--purple3"),
        purple4: withOpacity("--purple4"),
        purple5: withOpacity("--purple5"),
        purple6: withOpacity("--purple6"),
        purple7: withOpacity("--purple7"),
        purple8: withOpacity("--purple8"),
        purple9: withOpacity("--purple9"),
        fuchsia0: withOpacity("--fuchsia0"),
        fuchsia1: withOpacity("--fuchsia1"),
        fuchsia2: withOpacity("--fuchsia2"),
        fuchsia3: withOpacity("--fuchsia3"),
        fuchsia4: withOpacity("--fuchsia4"),
        fuchsia5: withOpacity("--fuchsia5"),
        fuchsia6: withOpacity("--fuchsia6"),
        fuchsia7: withOpacity("--fuchsia7"),
        fuchsia8: withOpacity("--fuchsia8"),
        fuchsia9: withOpacity("--fuchsia9"),
        pink0: withOpacity("--pink0"),
        pink1: withOpacity("--pink1"),
        pink2: withOpacity("--pink2"),
        pink3: withOpacity("--pink3"),
        pink4: withOpacity("--pink4"),
        pink5: withOpacity("--pink5"),
        pink6: withOpacity("--pink6"),
        pink7: withOpacity("--pink7"),
        pink8: withOpacity("--pink8"),
        pink9: withOpacity("--pink9"),
        rose0: withOpacity("--rose0"),
        rose1: withOpacity("--rose1"),
        rose2: withOpacity("--rose2"),
        rose3: withOpacity("--rose3"),
        rose4: withOpacity("--rose4"),
        rose5: withOpacity("--rose5"),
        rose6: withOpacity("--rose6"),
        rose7: withOpacity("--rose7"),
        rose8: withOpacity("--rose8"),
        rose9: withOpacity("--rose9"),
        blueGray: colors.blueGray,
        coolGray: colors.coolGray,
        gray: colors.gray,
        trueGray: colors.trueGray,
        warmGray: colors.warmGray,
        red: colors.red,
        orange: colors.orange,
        amber: colors.amber,
        yellow: colors.yellow,
        lime: colors.lime,
        green: colors.green,
        emerald: colors.emerald,
        teal: colors.teal,
        cyan: colors.cyan,
        sky: colors.sky,
        blue: colors.blue,
        indigo: colors.indigo,
        violet: colors.violet,
        purple: colors.purple,
        fuchsia: colors.fuchsia,
        pink: colors.pink,
        rose: colors.rose,
      },
      cursor: {
        grab: "grab",
        grabbing: "grabbing",
        "zoom-in": "zoom-in",
        "zoom-out": "zoom-out",
      },
      typography: (theme) => ({
        DEFAULT: {
          css: [
            {
              color: theme("colors.gray7"),
              '[class~="lead"]': {
                color: theme("colors.gray6"),
              },
              a: {
                color: theme("colors.gray9"),
              },
              strong: {
                color: theme("colors.gray9"),
              },
              "ol > li::before": {
                color: theme("colors.gray5"),
              },
              "ul > li::before": {
                backgroundColor: theme("colors.gray3"),
              },
              hr: {
                borderColor: theme("colors.gray2"),
              },
              blockquote: {
                color: theme("colors.gray9"),
                borderLeftColor: theme("colors.gray2"),
              },
              h1: {
                color: theme("colors.gray9"),
              },
              h2: {
                color: theme("colors.gray9"),
              },
              h3: {
                color: theme("colors.gray9"),
              },
              h4: {
                color: theme("colors.gray9"),
              },
              "figure figcaption": {
                color: theme("colors.gray5"),
              },
              code: {
                color: theme("colors.gray9"),
              },
              "a code": {
                color: theme("colors.gray9"),
              },
              pre: {
                color: theme("colors.gray2"),
                backgroundColor: theme("colors.gray8"),
              },
              thead: {
                color: theme("colors.gray9"),
                borderBottomColor: theme("colors.gray3"),
              },
              "tbody tr": {
                borderBottomColor: theme("colors.gray2"),
              },
            },
          ],
        },
      }),
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/line-clamp"),
    require("@tailwindcss/aspect-ratio"),
  ],
};
